<?php

class DefaultController extends Controller
{
    public  function filters()
    {
        return array(
            'accessControl'
        );
    }

    public function filter()
    {
        return array(
            array(
                'allow',
                'actions'=>array('index'),
                'users'=>array('@')//yêu cầu phải đăng nhập mới trước khi cho vào index
            ),
            array(
                'allow',
                'actions'=>array('login'),
                'users'=>array('*')//ai vào cũng được
            ),
            array(
                'denly',
                'actions'=>array('*')//từ chối các yêu cầu còn lại
            )
        );
    }
    public function accessRules()
    {
        return parent::accessRules(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
	{
		$this->render('index',array("content"=>"bcx"));
	}
    public function actionLogin()
    {
        $adminLogin=new AdminLoginForm();
        if(isset($_POST['AdminLoginForm']))
        {
            $adminLogin->attributes = $_POST['AdminLoginForm'];
            if ($adminLogin->validate()&&$adminLogin->login()){
                $this->redirect(array('index'));
            }
        }
        return $this->renderPartial('login',array('adminLogin'=>$adminLogin));
    }

}