<?php

class DefaultController extends Controller
{

    public function accessRules()
    {
        return parent::accessRules(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
	{
		$this->render('index',array("content"=>"bcx"));
	}
    public function actionLogin()
    {
        $adminLogin=new AdminLoginForm();
        if(isset($_POST['AdminLoginForm']))
        {
            $adminLogin->attributes = $_POST['AdminLoginForm'];
            if ($adminLogin->validate()&&$adminLogin->login()){
                $this->redirect(array('index'));
            }
        }
        return $this->renderPartial('login',array('adminLogin'=>$adminLogin));
    }

}